name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir k8s_info-tools
        echo "AMD64 build"
        make build_amd64
        mv k8s_info_amd64 k8s_info-tools
        echo "Darwin build"
        make build_darwin
        mv k8s_info_darwin k8s_info-tools
        echo "Power8 build"
        make build_power8
        mv k8s_info_power8 k8s_info-tools
        echo "ARM64 build"
        make build_arm64
        mv k8s_info_arm64 k8s_info-tools
        echo "Windows build"
        make build_windows
        mv k8s_info_windows k8s_info-tools
        tar cfz k8s_info-tools.tar.gz k8s_info-tools

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binary
      id: upload-k8s_info-tools
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./k8s_info-tools.tar.gz
        asset_name: k8s_info-tools.tar.gz
        asset_content_type: application/octet-stream
